
'use strict';

const STORE='streetKingsManagerV8';
const FIRST='streetKingsFirstBootV8';
const app=document.getElementById('app');
const modalRoot=document.getElementById('modal-root');
const toastRoot=document.getElementById('toast-root');

const TEAM_LIST=[
  {id:'talblick',name:'FC Talblick',city:'Katzenelnbogen',league:'L1',logo:'🦅',color:'#22c55e'},
  {id:'taunus',name:'Taunus Park FC',city:'Hahnstätten',league:'L1',logo:'🏔️',color:'#3b82f6'},
  {id:'limburg',name:'Limburg United',city:'Limburg',league:'L1',logo:'🏰',color:'#ef4444'},
  {id:'diezer',name:'Diezer SV',city:'Diez',league:'L1',logo:'🦁',color:'#60a5fa'},
  {id:'nassau',name:'Nassau FC',city:'Nassau',league:'L1',logo:'🦁',color:'#f4d03f'},
  {id:'bad-ems',name:'Bad Ems 1911',city:'Bad Ems',league:'L1',logo:'🌊',color:'#38bdf8'},
  {id:'aar-tal',name:'Aar Tal FC',city:'Aarbergen',league:'L1',logo:'🌲',color:'#22c55e'},
  {id:'vfr-einrich',name:'VfR Einrich',city:'Klingelbach',league:'L1',logo:'🌬️',color:'#94a3b8'},
  {id:'blau-weiss',name:'Blau-Weiss Allendorf',city:'Allendorf',league:'L2',logo:'⚜️',color:'#3b82f6'},
  {id:'tus-huen',name:'TuS Hünstätten',city:'Hünstätten',league:'L2',logo:'🐓',color:'#ef4444'},
  {id:'holzhausen',name:'SV Holzhausen',city:'Holzhausen',league:'L2',logo:'🌲',color:'#22c55e'},
  {id:'scheidt',name:'FC Scheidt',city:'Scheidt',league:'L2',logo:'⛪',color:'#60a5fa'},
  {id:'viktoria-berg',name:'Viktoria Berg',city:'Berg',league:'L2',logo:'⛏️',color:'#f4d03f'},
  {id:'lahn-blick',name:'SG Lahn Blick',city:'Lahnstein',league:'L2',logo:'🏞️',color:'#f59e0b'},
  {id:'zollhaus',name:'FC Zollhaus',city:'Zollhaus',league:'L2',logo:'🏠',color:'#94a3b8'},
  {id:'oberneisen',name:'SV Oberneisen',city:'Oberneisen',league:'L2',logo:'🍃',color:'#22c55e'},
  {id:'heistern',name:'RSV Heistern',city:'Heistern',league:'L2',logo:'🐎',color:'#d1d5db'},
  {id:'doersdorf',name:'FC Dörsdorf',city:'Dörsdorf',league:'L3',logo:'🦌',color:'#b45309'},
  {id:'rettert',name:'SV Rettert',city:'Rettert',league:'L3',logo:'🌳',color:'#22c55e'},
  {id:'eisenbach',name:'TuS Eisenbach',city:'Eisenbach',league:'L3',logo:'⚒️',color:'#94a3b8'},
  {id:'koersdorf',name:'SV Körsdorf',city:'Körsdorf',league:'L3',logo:'🍀',color:'#22c55e'},
  {id:'netzen',name:'FC Netzen',city:'Netzen',league:'L3',logo:'🎯',color:'#ef4444'},
  {id:'flacht',name:'SG Flacht',city:'Flacht',league:'L3',logo:'🌾',color:'#f4d03f'},
  {id:'niederneisen',name:'SV Niedereisen',city:'Niedereisen',league:'L3',logo:'🏰',color:'#ef4444'},
  {id:'kaldorf',name:'FC Kaldorf',city:'Kaldorf',league:'L3',logo:'🐗',color:'#111827'}
];
const LEAGUES={L1:{name:'Kreisliga A',level:1},L2:{name:'Kreisliga B',level:2},L3:{name:'Kreisliga C',level:3}};
const POS=['TW','ZDM','ZOM','LF','RF','ST','MS'];
const FIRST_NAMES=['Ilija','Leon','Zdravko','Tobias','Kristijan','Chris','Nils','Daniel','Dario','Noah','Rico','Matteo','Luca','Toni','Emir','Milan','Jonas','Felix','Elias','Paul','Finn','Mika','Jan','Ben'];
const LAST_NAMES=['Ponjavic','Müller','Kovac','Erb','Stojcevic','Schmidt','Fischer','Jovic','Hahn','Weber','Klein','Moretti','Salazar','Nakamura','Mendes','Roth','Keller','Wagner'];
const LOCAL_SPONSORS=[
 ['RHEINHOLZ','🪵'],['NOVA SERVICE','🌿'],['TALBLICK SPORT','🦅'],['AAR BÄCKEREI','🥨'],['EINRICH METZGEREI','🥩'],['KATZENELNBOGENER KAFFEEWERK','☕'],['AAR TAL GETRÄNKE','🥤'],['LAHN & LAND HOFLADEN','🌾'],['TAUNUS FAHRRADWERK','🚲'],['KATZENELNBOGEN AUTO SERVICE','🚗'],['EINRICH REIFEN','🛞'],['AAR APOTHEKE','💊'],['LAHN OPTIK','👓'],['TAUNUS FITNESS','🏋️'],['EINRICH SPORTSWEAR','👕'],['KATZENELNBOGEN FAHRSCHULE','🚦'],['AAR BAU & HOLZ','🪵'],['LAHN ELEKTRO','🔌'],['TAUNUS DACH & WAND','🏠'],['EINRICH GARTENWELT','🌳'],['KATZENELNBOGEN BLUMENHAUS','💐'],['AAR CAFÉ AM MARKT','🍰'],['LAHN PIZZA','🍕'],['TAUNUS GRILLSTUBE','🍔'],['EINRICH EISDIELE','🍦'],['KATZENELNBOGEN BUCHLADEN','📚'],['AAR COMPUTER SERVICE','💻'],['LAHN HANDY PUNKT','📱'],['TAUNUS WERKSTATT','🔧'],['EINRICH SCHLÜSSELDIENST','🔑'],['KATZENELNBOGEN REINIGUNG','🧽'],['AAR DRUCK & DESIGN','🖨️'],['LAHN MEDIA','📺'],['TAUNUS RADIO','📻'],['EINRICH EVENTSERVICE','🎪'],['KATZENELNBOGEN TAXI','🚕'],['AAR KURIER','📦'],['LAHN LOGISTIK','🚚'],['TAUNUS IMMOBILIEN','🏢'],['EINRICH VERSICHERUNG','🛡️'],['KATZENELNBOGEN FINANZSERVICE','💶'],['AAR REISEBÜRO','✈️'],['LAHN HOTEL','🛏️'],['TAUNUS CAMPING','⛺'],['EINRICH TIERMARKT','🐾'],['KATZENELNBOGEN TIERARZT','🐕'],['AAR FAHRRAD & SPORT','⚽'],['LAHN OUTDOOR','🥾'],['TAUNUS HOLZHANDEL','🪚'],['EINRICH BAUSTOFFE','🧱'],['KATZENELNBOGEN MARKT','🛒'],['AAR GETRÄNKEMARKT','🍺'],['LAHN BLECH & METALL','⚙️'],['TAUNUS DRUCKEREI','📰'],['REGIONALBANK AAR-EINRICH','🏦'],['KREISSPARKASSE RHEIN-LAHN','💳'],['AUTOHAUS EINRICH','🚘'],['FENSTER & TÜREN LAHN','🪟']
];
const STADIUM_UPGRADES={
 stands:['Tribünenausbau','👥','Kapazität +40',9000],field:['Spielfeldqualität','⚽','Heimbonus +2',11000],vip:['VIP-Lounge','💎','VIP-Erlös +8%',14000],shops:['Merchandise','👕','Merch +8%',10000],parking:['Parkplätze','🚗','Auslastung +4%',8000],catering:['Catering','🍔','Catering +8%',8500],entertainment:['Entertainment','🎪','Fans +5%',10000],training:['Trainingszentrum','🏋️','Entwicklung +3%',15000],youth:['Jugendakademie','🧒','Jugendqualität +5%',16000],tech:['Stadion-Technologie','📱','Sponsorbonus +4%',18000]
};
const DRAFTS={premium:{name:'Grand Kings Draft',price:5000000,count:6,pick:3,min:78,max:96},gold:{name:'Gold Draft',price:2000000,count:4,pick:1,min:72,max:82},silver:{name:'Silver Draft',price:800000,count:3,pick:1,min:58,max:72}};
const COACH_SPECIALTIES=['Pressing','Passing','Dribbling','Defensive Organisation','Set Pieces','Youth Development','Match Preparation','Fitness','Team Chemistry','Video Analysis'];

function uid(prefix='id'){return prefix+'_'+Math.random().toString(36).slice(2,10)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function choose(a){return a[Math.floor(Math.random()*a.length)]}
function money(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v||0)}
function dateStr(d){return new Date(d).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function avg(a,fn){return a.length?a.reduce((s,x,i)=>s+fn(x,i),0)/a.length:0}
function leagueTeams(lid){return Object.values(state.teams).filter(t=>t.league===lid)}
function currentTeam(){return state.teams[state.userTeamId]||state.teams.talblick}
function userLeague(){return currentTeam()?.league||'L1'}
function teamById(id){return state.teams[id]}
function playerById(id){for(const t of Object.values(state.teams)){const p=t.roster.find(x=>x.id===id);if(p)return {...p,sourceTeamId:t.id,sourceTeamName:t.name,sourceType:'club'}}return state.freeMarket.find(x=>x.id===id)?{...state.freeMarket.find(x=>x.id===id),sourceType:'market',sourceTeamId:null,sourceTeamName:'Freier Markt'}:null}
function positionLabel(p){return p==='TW'?'TW':p}
function eligibleGK(p){return p && (p.pos==='TW'||p.pos==='GK'||p.gk===true||String(p.pos).includes('TW'))}
function defaultCoords(){return [{x:50,y:84},{x:25,y:63},{x:75,y:63},{x:37,y:33},{x:63,y:33}]}
function lineupRole(team,p,index){const c=team.positions?.[p.id]||defaultCoords()[index]||{x:50,y:50};const inGoal=c.y>=76&&c.x>=34&&c.x<=66;const suitable=eligibleGK(p);return inGoal?{label:'TOR',rating:suitable?p.rating:Math.round(p.rating*.45),suitable,move:(suitable ? .75 : .18),inGoal:true}:{label:positionLabel(p.pos),rating:p.rating,suitable:true,move:1,inGoal:false}}
function teamPower(t){const five=t.roster.slice(0,5);return avg(five,(p,i)=>{const r=lineupRole(t,p,i);return r.inGoal&&!r.suitable?r.rating:r.rating})+(t.coachBoost||0)+(t.form||0)}

function createPlayer(name, pos, rating, value, teamId){
  const [first,last]=name.includes(' ')?name.split(' ').reduce((a,x,i)=>i? [a[0],a[1]+' '+x]:[x,''],[]):[name,''];
  return {id:uid('p'),name:name||`${first} ${last}`.trim(),pos,rating,age:rand(18,30),value,salary:Math.round(value/220),contractYears:rand(1,4),morale:rand(62,92),form:rand(55,88),fitness:rand(75,98),skills:{speed:rand(rating-8,rating+4),pass:rand(rating-7,rating+5),shoot:rand(rating-6,rating+6),def:rand(rating-6,rating+5),dribble:rand(rating-6,rating+6),stamina:rand(rating-4,rating+4),gk:pos==='TW'?rand(rating-3,rating+7):rand(15,55)},teamId}
}
function talblickRoster(){return [
  ['ILIJA','ZOM',76,1170000],['LEON','RF',78,1010000],['ZDRAVKO','LF / ZM / TW',82,870000],['TOBIAS','ST',68,770000],['KRISTIJAN','ZDM',65,730000],['CHRIS','MS',72,580000],['NILS','LF',69,480000],['DANIEL','MS',63,390000]
].map(x=>createPlayer(x[0],x[1],x[2],x[3],'talblick'))}
function makeTeam(t,i){
  const roster=t.id==='talblick'?talblickRoster():Array.from({length:8},(_,j)=>{const pos=choose(['TW','ZDM','ZOM','LF','RF','ST']);const base=(t.league==='L1'?rand(62,78):t.league==='L2'?rand(55,70):rand(46,65));return createPlayer(`${choose(FIRST_NAMES)} ${choose(LAST_NAMES)}`,pos,base,Math.round((base**2)*1250),t.id)});
  roster.forEach(p=>p.teamId=t.id);
  return {...t,roster,budget:t.id==='talblick'?245000:rand(160000,480000),fans:rand(500,2200),morale:rand(62,86),form:0,coachBoost:0,coachId:null,sponsorId:null,positions:Object.fromEntries(roster.slice(0,5).map((p,k)=>[p.id,defaultCoords()[k]])),stadium:{level:1,capacity:180,upgrades:Object.fromEntries(Object.keys(STADIUM_UPGRADES).map(k=>[k,1]))},financials:{income:0,expenses:0}}
}
function leagueStrength(t){return teamPower(t)+(t.id==='talblick'?4:0)}
function makeFixture(a,b,day){return {id:uid('fx'),date:day,home:a,away:b,played:false,homeScore:null,awayScore:null}}
function makeLeagueSchedule(lid,startDate){
 const teams=leagueTeams(lid).slice(); if(teams.length<2)return []; const arr=teams.slice(); if(arr.length%2)arr.push(null); const rounds=arr.length-1,half=[];
 for(let r=0;r<rounds;r++){const pairs=[];for(let i=0;i<arr.length/2;i++){const a=arr[i],b=arr[arr.length-1-i];if(a&&b)pairs.push([a,b])}half.push(pairs);arr.splice(1,0,arr.pop())}
 const out=[];let w=0;for(const pairs of half){for(const [a,b] of pairs)out.push(makeFixture(a.id,b.id,new Date(startDate.getTime()+w*7*86400000).toISOString()));w++}for(const pairs of half){for(const [a,b] of pairs)out.push(makeFixture(b.id,a.id,new Date(startDate.getTime()+w*7*86400000).toISOString()));w++}return out;
}
function makeSchedule(){const start=new Date(state.date);state.fixtures=[];['L1','L2','L3'].forEach(lid=>state.fixtures.push(...makeLeagueSchedule(lid,start)));state.seasonLength=16}
function standings(lid){
 const rows=leagueTeams(lid).map(t=>({id:t.id,name:t.name,played:0,w:0,d:0,l:0,gf:0,ga:0,pts:0}));
 const map=Object.fromEntries(rows.map(r=>[r.id,r]));
 state.fixtures.filter(f=>f.played&&map[f.home]&&map[f.away]).forEach(f=>{const h=map[f.home],a=map[f.away];h.played++;a.played++;h.gf+=f.homeScore;h.ga+=f.awayScore;a.gf+=f.awayScore;a.ga+=f.homeScore;if(f.homeScore>f.awayScore){h.w++;h.pts+=3;a.l++}else if(f.homeScore<f.awayScore){a.w++;a.pts+=3;h.l++}else{h.d++;a.d++;h.pts++;a.pts++}});
 rows.sort((a,b)=>b.pts-a.pts||((b.gf-b.ga)-(a.gf-a.ga))||b.gf-a.gf);return rows;
}
function nextFixture(){return state.fixtures.filter(f=>!f.played&&(f.home===state.userTeamId||f.away===state.userTeamId)).sort((a,b)=>new Date(a.date)-new Date(b.date))[0]}
function todayFixture(){return state.fixtures.find(f=>!f.played&&(f.home===state.userTeamId||f.away===state.userTeamId)&&dateStr(f.date)===dateStr(state.date))}

function initialState(){
 const teams=Object.fromEntries(TEAM_LIST.map((t,i)=>[t.id,makeTeam(t,i)]));
 const sponsors=LOCAL_SPONSORS.map((s,i)=>({id:'sp'+i,name:s[0],emoji:s[1],tier:1+Math.floor(i/15),weekly:6000+i*450,bonus:1+i%5,cancelFee:15000+i*2200}));
 const coaches=Array.from({length:150},(_,i)=>({id:'c'+i,name:`${choose(FIRST_NAMES)} ${choose(LAST_NAMES)}`,age:rand(34,67),specialty:choose(COACH_SPECIALTIES),boost:rand(2,8),price:rand(9000,65000),contractWeeks:26,weakness:choose(['Rotation','Medien','Jugend','Taktik','Fitness'])}));
 const freeMarket=Array.from({length:60},(_,i)=>createPlayer(`${choose(FIRST_NAMES)} ${choose(LAST_NAMES)}`,choose(POS),rand(52,82),rand(90000,620000),null));
 const st={version:8,manager:'Manager',userTeamId:'talblick',season:1,week:1,date:new Date('2026-09-01T18:00:00').toISOString(),teams,freeMarket,sponsors,coaches,fixtures:[],news:[],messages:[],offers:[],inquiries:[],playerOffers:[],drafts:[],coachOffers:[],selectedDraft:null,marketFilter:'all',page:'home',formation:'1-2-2',seasonLength:16,liveMatch:null,lineupDraft:null,settings:{},credits:0,calendarOpen:false,booted:false};
 state=st;makeSchedule();
 addNews('Willkommen bei Street Kings Manager', 'Dein Weg mit FC Talblick beginnt jetzt.','system');return st;
}
let state;
function load(){try{const raw=localStorage.getItem(STORE);if(!raw)return initialState();const s=JSON.parse(raw);state={...initialState(),...s,teams:s.teams||initialState().teams,playerOffers:s.playerOffers||[],seasonLength:s.seasonLength||16};return state}catch(e){return initialState()}}
function save(){state.savedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));toast('Gespeichert','Dein Spielstand wurde gespeichert.')}
function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='street-kings-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);toast('Export bereit','Die JSON-Datei wurde erstellt.')}
function importSave(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const s=JSON.parse(r.result);if(!s.teams||!s.fixtures)throw Error('Ungültiger Spielstand');state=s;save();location.reload()}catch(e){toast('Import fehlgeschlagen',e.message)}};r.readAsText(f)};i.click()}
function resetGame(){if(!confirm('Neues Spiel starten? Der aktuelle Spielstand wird gelöscht.'))return;localStorage.removeItem(STORE);location.reload()}
function addNews(title,text,tag='INFO'){state.news.unshift({id:uid('n'),date:Date.now(),title,text,tag});state.news=state.news.slice(0,28)}
function toast(title,text){const el=document.createElement('div');el.className='toast';el.innerHTML=`<b>${esc(title)}</b><small>${esc(text||'')}</small>`;toastRoot.appendChild(el);setTimeout(()=>el.remove(),2800)}
function modal(title,body,actions=''){modalRoot.innerHTML=`<div class="modal-backdrop" data-close-modal><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>${title}</h3><button class="icon-btn" data-close-modal>✕</button></div>${body}${actions}</div></div>`}
function closeModal(){modalRoot.innerHTML=''}

function boot(){load();render();if(!localStorage.getItem(FIRST)){setTimeout(()=>{modal('STREET KINGS MANAGER · START',`<div class="welcome"><div class="kicker">EINRICH EDITION</div><h2>Wähle deinen Verein</h2><p class="note">FC Talblick ist voreingestellt. Du kannst aber jeden Club der Region übernehmen.</p><div style="max-height:300px;overflow:auto">${TEAM_LIST.map(t=>`<button class="player-row" style="width:100%" data-start-team="${t.id}"><div class="table-logo">${t.logo}</div><div><strong>${esc(t.name)}</strong><span>${esc(t.city)} · ${esc(LEAGUES[t.league].name)}</span></div><b>›</b></button>`).join('')}</div></div>`);},250)}}
function render(){app.innerHTML=`<div class="screen"><div class="topbar">${topbar()}</div><main class="page">${renderPage()}</main></div>${bottomNav()}`}
function topbar(){const t=currentTeam();return `<div class="brand"><div class="brand-mark">${t.logo}</div><div><strong>STREET KINGS</strong><small>MANAGER · ${esc(t.city)}</small></div></div><div class="top-spacer"></div><div class="season-mini">S${state.season} · W${state.week}</div><div class="money">${money(t.budget)}</div>`}
function bottomNav(){return `<nav class="bottom-nav">${[['home','🏠','Home'],['club','🛡️','Verein'],['games','⚽','Spielen'],['market','🛒','Markt'],['menu','☰','Menü']].map(([p,i,l])=>`<button class="${state.page===p?'active':''}" data-page="${p}"><span>${i}</span>${l}</button>`).join('')}</nav>`}
function pageHead(title,sub,extra=''){return `<div class="page-head"><div><div class="kicker">STREET KINGS · ${esc(currentTeam().city)}</div><h1>${title}</h1><p>${esc(sub)}</p></div>${extra}</div>`}
function card(title,body,cls=''){return `<section class="card ${cls}">${title?`<div class="section-head"><h2>${title}</h2></div>`:''}${body}</section>`}

function renderPage(){
 switch(state.page){case'home':return homePage();case'club':return clubPage();case'games':return gamesPage();case'market':return marketPage();case'menu':return menuPage();case'league':return leaguePage();case'team':return teamPage();case'tactics':return tacticsPage();case'transfers':return transfersPage();case'sponsors':return sponsorsPage();case'coaches':return coachesPage();case'draft':return draftPage();case'stadium':return stadiumPage();case'calendar':return calendarPage();case'finances':return financesPage();case'news':return newsPage();case'settings':return settingsPage();case'youth':return youthPage();default:return homePage()}}

function homePage(){const t=currentTeam(),fx=nextFixture();return pageHead('Street Kings Manager','Einrich Edition')+`<section class="hero"><div class="hero-title">STREET KINGS<span>MANAGER</span></div><div class="hero-sub">PIXEL FOOTBALL · KATZENELNBOGEN · EINRICH</div></section>${fx?card('Nächstes Spiel',`<div class="next-match"><div class="kicker">${dateStr(fx.date)} · ${fx.home===t.id?'HEIM':'AUSWÄRTS'}</div><div class="matchup">${esc(teamById(fx.home).name)} <span class="tag-gold">vs</span> ${esc(teamById(fx.away).name)}</div><small>Kreisliga ${LEAGUES[teamById(fx.home).league].name} · Street Soccer</small><div style="margin-top:10px"><button class="gold-btn wide" data-simulate="${fx.id}">SPIEL VORBEREITEN</button></div></div>`):''}${card('Schnellzugriff',`<div class="action-grid"><button class="action-tile" data-page="team"><b>🛡️</b><small>VEREIN</small></button><button class="action-tile" data-page="tactics"><b>📋</b><small>TEAM</small></button><button class="action-tile" data-page="games"><b>⚽</b><small>SPIELEN</small></button><button class="action-tile" data-page="transfers"><b>↔️</b><small>TRANSFERS</small></button><button class="action-tile" data-page="market"><b>🛒</b><small>MARKTPLATZ</small></button><button class="action-tile" data-page="sponsors"><b>🤝</b><small>SPONSOREN</small></button><button class="action-tile" data-page="stadium"><b>🏟️</b><small>STADION</small></button><button class="action-tile" data-page="league"><b>🏆</b><small>LIGA</small></button></div>`)}${card('Aktuelle Meldungen',state.news.slice(0,5).map(n=>`<div class="news-item"><span class="tag">${esc(n.tag)}</span><b>${esc(n.title)}</b><small>${esc(n.text)}</small></div>`).join('')||'<div class="empty">Keine Meldungen.</div>')}`}

function clubPage(){const t=currentTeam(),top=t.roster.slice().sort((a,b)=>b.value-a.value).slice(0,6);return pageHead('Verein',`${t.name} · ${t.city}`)+card('',`<div class="grid3"><div class="stat"><b>${money(t.budget)}</b><small>Budget</small></div><div class="stat"><b>${t.fans}</b><small>Fans</small></div><div class="stat"><b>${Math.round(teamPower(t))}</b><small>Rating</small></div></div>`)+card('Kader',top.map(p=>`<div class="player-row"><div class="table-logo">${p.pos==='TW'?'🧤':'⚽'}</div><div><strong>${esc(p.name)}</strong><span>${esc(p.pos)} · ${p.age} J. · ${p.form}% Form</span></div><b>${p.rating}</b></div>`).join(''))+card('Verein',`<div class="action-grid"><button class="action-tile" data-page="tactics"><b>📋</b><small>AUFSTELLUNG</small></button><button class="action-tile" data-page="sponsors"><b>🤝</b><small>SPONSOREN</small></button><button class="action-tile" data-page="coaches"><b>🧠</b><small>COACH</small></button><button class="action-tile" data-page="youth"><b>🧒</b><small>JUGEND</small></button><button class="action-tile" data-page="stadium"><b>🏟️</b><small>STADION</small></button><button class="action-tile" data-page="finances"><b>💶</b><small>FINANZEN</small></button></div>`)}

function tacticsPage(){const t=currentTeam();t.positions=t.positions||{};const players=t.roster.slice(0,5);return pageHead('Taktik','Spieler per Touch verschieben · 5er-System',`<button class="ghost-btn" data-page="team">Zurück</button>`)+card('Formation',`<div class="grid3">${['1-2-2','1-1-2','1-3-1'].map(f=>`<button class="seg ${state.formation===f?'active':''}" data-formation="${f}">${f}</button>`).join('')}</div><div style="margin-top:10px" class="field-mobile" data-lineup-field><div class="field-line mid"></div><div class="field-line center"></div><div class="field-line box-top"></div><div class="field-line box-bottom"></div><div class="field-line goal-top"></div><div class="field-line goal-bottom"></div>${players.map((p,i)=>{const c=t.positions?.[p.id]||defaultCoords()[i];const r=lineupRole(t,p,i);return `<button class="field-player ${r.inGoal&&!r.suitable?'gk-warn':''}" data-drag-player="${p.id}" style="left:${c.x}%;top:${c.y}%"><span class="drag-grip">✥</span><div class="table-logo">${r.inGoal?'🧤':'⚽'}</div><b>${esc(p.name)}</b><span>${esc(r.label)} ${r.rating}${r.inGoal&&!r.suitable?' · ungeeignet':''}</span></button>`}).join('')}</div><p class="note">Zieh einen Spieler in den Torraum. Nur echte TW sind dort effektiv; ein Feldspieler erhält einen starken Mobilitäts- und Rating-Malus.</p>`)+card('Mannschaftswerte',`<div class="bar-row"><span>OFF</span><b>${Math.round(avg(players,p=>p.skills.shoot))}</b><div class="bar"><i style="width:${avg(players,p=>p.skills.shoot)}%"></i></div></div><div class="bar-row"><span>PASS</span><b>${Math.round(avg(players,p=>p.skills.pass))}</b><div class="bar"><i style="width:${avg(players,p=>p.skills.pass)}%"></i></div></div><div class="bar-row"><span>DEF</span><b>${Math.round(avg(players,p=>p.skills.def))}</b><div class="bar"><i style="width:${avg(players,p=>p.skills.def)}%"></i></div></div>`) }

function gamesPage(){const fx=state.fixtures.filter(f=>!f.played&&(f.home===state.userTeamId||f.away===state.userTeamId)).slice(0,10);return pageHead('Spielen','Saison, Spieltage und Matchday')+card('Nächste Partien',fx.map(f=>`<div class="fixture-row"><div>${f.home===state.userTeamId?'🏠':'✈️'}</div><div class="fixture-main"><strong>${esc(teamById(f.home).name)} vs ${esc(teamById(f.away).name)}</strong><span>${dateStr(f.date)} · ${LEAGUES[teamById(f.home).league].name}</span></div><button class="small-btn gold" data-simulate="${f.id}">SPIEL</button></div>`).join('')||'<div class="empty">Keine offenen Spiele.</div>')+card('Modi',`<div class="action-grid"><button class="action-tile" data-page="calendar"><b>📅</b><small>KALENDER</small></button><button class="action-tile" data-page="league"><b>🏆</b><small>TABELLE</small></button></div>`)}

function leaguePage(){const tabs=['L1','L2','L3'];return pageHead('Liga','Alle drei Spielklassen · 25 Teams')+tabs.map(lid=>{const rows=standings(lid);return card(`${lid==='L1'?'👑':lid==='L2'?'⚪':'🟠'} ${LEAGUES[lid].name}`,rows.map((r,i)=>{const t=teamById(r.id);return `<div class="table-row ${t.id===state.userTeamId?'me':''}"><b>${i+1}</b><div class="table-logo">${t.logo}</div><div class="table-name"><strong>${esc(t.name)}</strong><small>${esc(t.city)}</small></div><span class="record">${r.w}-${r.d}-${r.l}</span><b class="points">${r.pts}</b></div>`}).join(''))}).join('')+card('Auf- & Abstieg',`<div class="grid2"><div class="stat"><b>▲ 1–2</b><small>Aufstieg</small></div><div class="stat"><b>▼ letzte 2</b><small>Abstieg</small></div></div>`)}
function teamPage(){const t=currentTeam();return pageHead(t.name,`${t.city} · ${LEAGUES[t.league].name}`)+card('',`<div class="hero"><div class="hero-title">${t.logo} ${esc(t.name)}<span style="font-size:22px">${esc(t.city)}</span></div><div class="hero-sub">MEHR ALS EIN VEREIN</div></div>`)+card('Vereinsbereiche',`<div class="action-grid"><button class="action-tile" data-page="tactics"><b>📋</b><small>TAKTIK</small></button><button class="action-tile" data-page="transfers"><b>↔️</b><small>TRANSFERS</small></button><button class="action-tile" data-page="coaches"><b>🧠</b><small>COACH</small></button><button class="action-tile" data-page="sponsors"><b>🤝</b><small>SPONSOREN</small></button><button class="action-tile" data-page="stadium"><b>🏟️</b><small>STADION</small></button><button class="action-tile" data-page="youth"><b>🧒</b><small>JUGEND</small></button></div>`)}
function generateIncomingPlayerOffers(){const t=currentTeam();const targets=t.roster.filter(p=>p.rating>=68).sort((a,b)=>b.value-a.value).slice(0,4);const others=TEAM_LIST.filter(x=>x.id!==t.id);targets.forEach(p=>{if(state.playerOffers.some(o=>o.playerId===p.id&&o.status==='pending'))return;if(Math.random()>.5)return;const club=choose(others),amount=Math.round(p.value*(.9+Math.random()*.2));state.playerOffers.unshift({id:uid('pof'),playerId:p.id,playerName:p.name,teamId:club.id,teamName:club.name,amount,deadlineWeek:state.week+rand(2,5),status:'pending'});addNews('Spielerinteresse',`${club.name} fragt ${p.name} an.`,'TRANSFER')});state.playerOffers=state.playerOffers.slice(0,12)}
function simulateOtherFixturesOnDate(dateIso,excludeId){state.fixtures.filter(f=>!f.played&&f.date===dateIso&&f.id!==excludeId).forEach(f=>{const h=teamById(f.home),a=teamById(f.away);const hs=teamPower(h)+rand(-8,8),as=teamPower(a)+rand(-8,8);f.homeScore=clamp(Math.round(hs/40+rand(0,1)),0,7);f.awayScore=clamp(Math.round(as/42+rand(0,1)),0,7);f.played=true})}
function endWeek(){state.week++;state.date=new Date(new Date(state.date).getTime()+7*86400000).toISOString();Object.values(state.teams).forEach(t=>{t.roster.forEach(p=>{p.fitness=clamp(p.fitness-rand(0,3)+5,45,100);p.form=clamp(p.form+rand(-3,3),40,100);p.morale=clamp(p.morale+rand(-2,3),40,100);});if(t.sponsorId){const s=state.sponsors.find(x=>x.id===t.sponsorId);if(s){t.budget+=s.weekly;t.financials.income+=s.weekly}}const wages=t.roster.reduce((n,p)=>n+p.salary,0);t.budget-=wages;t.financials.expenses+=wages;if(t.coachId){const c=state.coaches.find(x=>x.id===t.coachId);if(c){c.contractWeeks=Math.max(0,(c.contractWeeks||26)-1);if(c.contractWeeks===0){t.coachId=null;t.coachBoost=0;addNews('Coachvertrag beendet',`${c.name} verlässt ${t.name}.`,'COACH')}}}});generateIncomingPlayerOffers();if(state.week>state.seasonLength)advanceSeason();save()}
function advanceSeason(){const l1=standings('L1'),l2=standings('L2'),l3=standings('L3');l1.slice(-2).forEach(r=>teamById(r.id).league='L2');l2.slice(0,2).forEach(r=>teamById(r.id).league='L1');l2.slice(-2).forEach(r=>teamById(r.id).league='L3');l3.slice(0,2).forEach(r=>teamById(r.id).league='L2');state.season++;state.week=1;state.date=new Date(state.date).toISOString();Object.values(state.teams).forEach(t=>t.roster.forEach(p=>{p.age++;p.rating=clamp(p.rating+rand(-2,2),35,96);p.value=Math.round(p.value*(1+(p.rating-65)/300))}));makeSchedule();addNews('Neue Saison',`Saison ${state.season} beginnt. Auf- und Abstieg abgeschlossen.`,'LIGA')}

function transfersPage(){const open=state.offers.filter(o=>['pending','countered','accepted','rejected'].includes(o.status)).slice(0,10);const incoming=state.playerOffers.filter(o=>o.status==='pending');return pageHead('Transfers','Verhandeln · Anfragen · Tausch',`<button class="gold-btn" data-page="market">MARKT</button>`)+card('Angebote für deinen Kader',incoming.map(o=>`<div class="offer-row"><div class="offer-main"><strong>${esc(o.playerName)}</strong><span>${esc(o.teamName)} · ${money(o.amount)} · bis Woche ${o.deadlineWeek}</span></div><div><button class="small-btn gold" data-player-offer-accept="${o.id}">ANNEHMEN</button><button class="small-btn" data-player-offer-reject="${o.id}">ABLEHNEN</button></div></div>`).join('')||'<div class="empty">Keine Angebote an deine Spieler.</div>')+card('Transferkalender',`<div class="calendar-now"><span>HEUTE</span><b>${dateStr(state.date)}</b><span>${open.filter(o=>o.status==='pending').length} offen</span></div>${open.filter(o=>o.status==='pending').slice(0,6).map(o=>`<div class="calendar-item"><div class="day">${o.replyDate?dateStr(o.replyDate):'2–5T'}</div><div><strong>${esc(o.playerName)}</strong><small>${esc(o.fromName)} · Antwort steht aus</small></div><span class="dot"></span></div>`).join('')}`)+card('Angebote & Antworten',open.map(o=>`<div class="offer-row"><div class="offer-main"><strong>${esc(o.playerName)}</strong><span>${esc(o.fromName)} · ${o.years} Jahre · ${money(o.salary)}/W</span></div><div><b class="tag-gold">${esc(o.status.toUpperCase())}</b>${o.status==='countered'?`<button class="small-btn gold" data-accept-counter="${o.id}">ANNEHMEN</button>`:''}</div></div>`).join('')||'<div class="empty">Noch keine Vorgänge.</div>')}

function marketPage(){
 let players=[];
 Object.values(state.teams).forEach(tm=>{if(tm.id!==state.userTeamId)tm.roster.forEach(p=>players.push({...p,sourceTeamId:tm.id,sourceTeamName:tm.name,sourceType:'club'}))});
 players.push(...state.freeMarket.map(p=>({...p,sourceType:'market',sourceTeamId:null,sourceTeamName:'Freier Markt'})));
 players=players.filter(p=>state.marketFilter==='all'||p.pos===state.marketFilter).sort((a,b)=>{const at=a.sourceTeamName==='FC Talblick'?1:0,bt=b.sourceTeamName==='FC Talblick'?1:0;return bt-at||b.rating-a.rating}).slice(0,90);
 return pageHead('Marktplatz','Keine Sofortkäufe · jeder Transfer ist Verhandlung',`<button class="ghost-btn" data-page="transfers">VORGÄNGE</button>`)
 +card('Filter',`<div class="filters">${['all','TW','ZDM','ZOM','LF','RF','ST'].map(f=>`<button class="seg ${state.marketFilter===f?'active':''}" data-market-filter="${f}">${f==='all'?'Alle':f}</button>`).join('')}</div>`)
 +card('Spieler',players.map(p=>`<div class="market-row"><div class="table-logo">${eligibleGK(p)?'🧤':'⚽'}</div><div class="market-player"><strong>${esc(p.name)}</strong><span>${esc(p.pos)} · ${p.age} J. · ${esc(p.sourceTeamName)}</span><div><b>${p.rating}</b> <small style="color:var(--muted)">${money(p.value)}</small></div></div><div class="market-actions"><button class="small-btn gold" data-offer="${p.id}">ANGEBOT</button><button class="small-btn" data-inquiry="${p.id}">ANFRAGE</button>${p.sourceType==='club'?`<button class="small-btn" data-trade="${p.id}">HANDEL</button>`:''}</div></div>`).join(''))
}


function sponsorsPage(){const t=currentTeam();return pageHead('Sponsoren','56 Partner aus Katzenelnbogen und Umgebung')+card('Aktuell',t.sponsorId?(()=>{const s=state.sponsors.find(x=>x.id===t.sponsorId);return `<div class="sponsor-row"><div class="sponsor-emoji">${s.emoji}</div><div class="sponsor-main"><strong>${esc(s.name)}</strong><span>${money(s.weekly)}/Woche · +${s.bonus}% Bonus</span></div><button class="small-btn red" data-sponsor-end>BEENDEN</button></div>`})():'<div class="empty">Noch kein Hauptsponsor. Verhandle einen Vertrag.</div>')+card('Partnerbörse',state.sponsors.map(s=>`<div class="sponsor-row"><div class="sponsor-emoji">${s.emoji}</div><div class="sponsor-main"><strong>${esc(s.name)}</strong><span>Stufe ${s.tier} · ${money(s.weekly)}/Woche · +${s.bonus}%</span></div><button class="small-btn gold" data-sponsor="${s.id}">${t.sponsorId===s.id?'AKTIV':'VERTRAG'}</button></div>`).join(''))}

function coachesPage(){const t=currentTeam();const list=state.coaches.slice().sort((a,b)=>b.boost-a.boost).slice(0,80);return pageHead('Coach','150 Coaches · Spezialisten · Verträge')+card('Aktueller Coach',t.coachId?(()=>{const c=state.coaches.find(x=>x.id===t.coachId);return `<div class="coach-row"><div class="table-logo">🧠</div><div class="coach-main"><strong>${esc(c.name)}</strong><span>${esc(c.specialty)} · +${c.boost}% · ${c.contractWeeks} Wochen</span></div><button class="small-btn red" data-fire-coach>BEENDEN</button></div>`})():'<div class="empty">Noch kein Coach.</div>')+card('Coach-Markt',list.map(c=>`<div class="coach-row"><div class="table-logo">🧠</div><div class="coach-main"><strong>${esc(c.name)}</strong><span>${esc(c.specialty)} · ${c.age} J.</span><small class="coach-badge">+${c.boost}% · ${money(c.price)}</small></div><button class="small-btn gold" data-hire-coach="${c.id}">HIRE</button></div>`).join(''))}
function draftPage(){return pageHead('Draft','Talente rekrutieren · mehrere Pakete')+Object.entries(DRAFTS).map(([k,d])=>card(`${d.name}`,`<div class="grid2"><div class="stat"><b>${d.count}</b><small>Spieler</small></div><div class="stat"><b>${d.pick}</b><small>Auswahl</small></div></div><p class="note">Rating ${d.min}–${d.max}. ${money(d.price)}.</p><button class="gold-btn wide" data-draft="${k}">DRAFT ÖFFNEN</button>`)).join('')}
function stadiumPage(){const t=currentTeam();return pageHead('Arena',`${t.name} · Umbau sichtbar`, `<button class="ghost-btn" data-rename-stadium>UMBENENNEN</button>`)+card('',`<div class="stadium-scene ${state.building?'building':''}"><div class="night-sky"></div><div class="stadium-lights left"></div><div class="stadium-lights right"></div><div class="stadium-bowl"></div><div class="build-badge">🏗️ UMBAU LÄUFT…</div></div><div class="grid3" style="margin-top:9px"><div class="stat"><b>${t.stadium.capacity}</b><small>Plätze</small></div><div class="stat"><b>Lvl ${t.stadium.level}</b><small>Arena</small></div><div class="stat"><b>${money(t.budget)}</b><small>Budget</small></div></div>`)+card('Ausbau',Object.entries(STADIUM_UPGRADES).map(([k,v])=>`<div class="upgrade-row"><div class="upgrade-main"><strong>${v[1]} ${esc(v[0])}</strong><span>${esc(v[2])} · Lvl ${t.stadium.upgrades[k]}</span></div><b>${money(Math.round(v[3]*Math.pow(1.65,t.stadium.upgrades[k]-1)))}</b><button class="small-btn gold" data-upgrade="${k}">+</button></div>`).join(''))}
function calendarPage(){const games=state.fixtures.filter(f=>f.home===state.userTeamId||f.away===state.userTeamId).sort((a,b)=>new Date(a.date)-new Date(b.date));return pageHead('Kalender','Saisonplan · Transfers · Termine')+card('Saisonplan',games.map(f=>`<div class="calendar-item"><div class="day">${dateStr(f.date)}</div><div><strong>${esc(teamById(f.home).name)} vs ${esc(teamById(f.away).name)}</strong><small>${f.played?`${f.homeScore}:${f.awayScore}`:'offen'}</small></div><span class="dot" style="background:${f.played?'#61706a':'#f4d03f'}"></span></div>`).join(''))}
function financesPage(){const t=currentTeam();const income=Math.round(t.financials.income),expenses=Math.round(t.financials.expenses);return pageHead('Finanzen','Einnahmen · Ausgaben · Investitionen')+card('',`<div class="grid3"><div class="stat"><b>${money(t.budget)}</b><small>Budget</small></div><div class="stat"><b>${money(income)}</b><small>Einnahmen</small></div><div class="stat"><b>${money(expenses)}</b><small>Ausgaben</small></div></div>`)+card('Wirtschaft',`<div class="news-item"><b>🏟️ Spieltagseinnahmen</b><small>Ticket, VIP, Catering, Merch, Sponsor</small></div><div class="news-item"><b>💼 Spielergehälter</b><small>Wöchentlich auf Basis der Verträge</small></div><div class="news-item"><b>🏦 Kredit</b><small>Verfügbar über Vereinsfinanzen</small></div>`) }
function newsPage(){return pageHead('Nachrichten','Verein · Transfers · Liga · Sponsoren')+card('',state.news.map(n=>`<div class="news-item"><span class="tag">${esc(n.tag)}</span><b>${esc(n.title)}</b><small>${esc(n.text)}</small></div>`).join('')||'<div class="empty">Noch keine Nachrichten.</div>')}
function youthPage(){const t=currentTeam();return pageHead('Jugendakademie','Talente entwickeln · Einrich Nachwuchs')+card('',`<div class="grid3"><div class="stat"><b>Lvl ${t.stadium.upgrades.youth}</b><small>Akademie</small></div><div class="stat"><b>${Math.max(1,t.stadium.upgrades.youth+1)}</b><small>Talente/Saison</small></div><div class="stat"><b>+${t.stadium.upgrades.youth*5}%</b><small>Qualität</small></div></div><button class="gold-btn wide" data-youth-scout>SCOUTING-ABLAUF</button><p class="note">Ein Ausbau der Jugendakademie verbessert die Qualität kommender Talente.</p>`)}
function menuPage(){return pageHead('Menü','Spielverwaltung und Management')+card('',`<div class="action-grid"><button class="action-tile" data-page="league"><b>🏆</b><small>LIGA & TABELLEN</small></button><button class="action-tile" data-page="team"><b>🛡️</b><small>TEAM ÜBERSICHT</small></button><button class="action-tile" data-page="calendar"><b>📅</b><small>KALENDER</small></button><button class="action-tile" data-page="news"><b>📰</b><small>NACHRICHTEN</small></button><button class="action-tile" data-page="draft"><b>🎯</b><small>DRAFT</small></button><button class="action-tile" data-page="coaches"><b>🧠</b><small>COACHES</small></button><button class="action-tile" data-page="sponsors"><b>🤝</b><small>SPONSOREN</small></button><button class="action-tile" data-page="stadium"><b>🏟️</b><small>ARENA</small></button><button class="action-tile" data-page="settings"><b>⚙️</b><small>EINSTELLUNGEN</small></button></div>`)}
function settingsPage(){return pageHead('Einstellungen','Savegames · Managerprofil · Spielstart')+card('Managerprofil',`<label class="label">Managername<input class="input" id="manager-name" value="${esc(state.manager)}"></label><label class="label">Vereinsname<input class="input" id="club-name" value="${esc(currentTeam().name)}"></label><button class="gold-btn wide" data-save-profile>SPEICHERN</button><p class="note">Zuletzt gespeichert: ${state.savedAt?new Date(state.savedAt).toLocaleString('de-DE'):'noch nie'}</p>`)+card('Spielstand',`<div class="action-grid"><button class="action-tile" data-save-game><b>💾</b><small>SPEICHERN</small></button><button class="action-tile" data-export><b>↑</b><small>EXPORTIEREN</small></button><button class="action-tile" data-import><b>↓</b><small>IMPORTIEREN</small></button><button class="action-tile danger" data-reset><b>↻</b><small>NEUES SPIEL</small></button></div>`)+card('Version 8',`<p class="note">Großes Fußball-Update: Coachsystem, Draft, Sponsoren, Stadion, Kalender, Finanzen, Transfers, Gegenangebote, Team-Entwicklung, komplette 3-Liga-Tabelle und Live-Match-Engine.</p>`)}

function openOffer(id,mode='offer'){const p=playerById(id);if(!p)return;const t=currentTeam();const source=p.sourceTeamName||'Freier Markt';const suggested=Math.round((p.value||300000)*.86);modal(`${mode==='trade'?'TAUSCHANGEBOT':'VERTRAGSANGEBOT'} · ${esc(p.name)}`,`<div class="contract-paper"><div class="kicker">STREET KINGS TRANSFERBÜRO</div><h2>${esc(p.name)}</h2><p class="note">${esc(source)} · ${esc(p.pos)} · ${p.rating} OVR · Marktwert ${money(p.value)}</p><div class="form-grid"><label class="label">Ablöse (€)<input class="input" id="offer-fee" type="number" value="${suggested}"></label><label class="label">Gehalt/Woche<input class="input" id="offer-salary" type="number" value="${Math.round(p.salary*1.1)}"></label><label class="label">Jahre<select class="input" id="offer-years"><option>1</option><option selected>2</option><option>3</option><option>4</option><option>5</option></select></label><label class="label">Einsatzbonus<input class="input" id="offer-bonus" type="number" value="250"></label></div>${mode==='trade'&&p.sourceType==='club'?`<label class="label">Tauschspieler<select class="input" id="trade-player"><option value="">Keinen anbieten</option>${t.roster.slice(5).map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.rating}</option>`).join('')}</select></label>`:''}<label class="label">Spaßklausel / Beschreibung<textarea class="input" id="offer-note" rows="3" placeholder="z.B. Stammplatz, Wohnung, Lieblingssong beim Heimspiel…"></textarea></label><p class="contract-summary">📅 Antwortfenster: 2–5 Tage · Der Manager kann annehmen, ablehnen oder kontern.</p><button class="gold-btn wide" data-send-offer="${id}" data-offer-mode="${mode}">ANGEBOT SENDEN</button></div>`)}
function sendOffer(id,mode){const p=playerById(id),t=currentTeam();if(!p)return;const fee=Number(document.getElementById('offer-fee').value)||0,salary=Number(document.getElementById('offer-salary').value)||0,years=Number(document.getElementById('offer-years').value)||2;const tradePlayer=document.getElementById('trade-player')?.value||null;if(fee>t.budget)return toast('Budget reicht nicht','Ablöse überschreitet dein Budget.');const o={id:uid('offer'),playerId:id,playerName:p.name,fromId:p.sourceTeamId,fromName:p.sourceTeamName||'Freier Markt',fee,salary,years,bonus:Number(document.getElementById('offer-bonus').value)||0,note:document.getElementById('offer-note').value||'',tradePlayer,mode,status:'pending',created:Date.now(),replyDate:new Date(Date.now()+(rand(2,5)*86400000)).toISOString()};state.offers.unshift(o);closeModal();save();toast('Angebot verschickt',`${p.name} · Antwort folgt im Kalender.`);}
function resolveOffers(){let changed=false;state.offers.filter(o=>o.status==='pending'&&new Date(o.replyDate)<=new Date()).forEach(o=>{changed=true;const p=playerById(o.playerId);if(!p){o.status='rejected';o.answer='Spieler nicht mehr verfügbar.';return}const ratio=o.fee/Math.max(1,p.value),roll=Math.random();if(ratio>1.02||roll<ratio*.55){if(p.sourceType==='club'&&o.fromId){teamById(o.fromId).roster=teamById(o.fromId).roster.filter(x=>x.id!==o.playerId)}else state.freeMarket=state.freeMarket.filter(x=>x.id!==o.playerId);currentTeam().budget-=o.fee;currentTeam().roster.push({...p,id:uid('p'),teamId:state.userTeamId,salary:o.salary,contractYears:o.years});o.status='accepted';o.answer='Deal akzeptiert.';addNews('Transfer abgeschlossen',`${p.name} kommt zu ${currentTeam().name}.`,'MARKT')}else if(ratio>.78||roll<.82){o.status='countered';o.counterFee=Math.round(Math.max(o.fee+15000,p.value*.98));o.counterSalary=Math.round(o.salary*1.12);o.answer='Manager schickt ein Gegenangebot.'}else{o.status='rejected';o.answer='Manager lehnt ab.';addNews('Transfer abgelehnt',`${p.name} bleibt bei ${o.fromName}.`,'MARKT')}});if(changed)save()}
function hireCoach(id){const c=state.coaches.find(x=>x.id===id),t=currentTeam();if(!c)return;if(t.budget<c.price)return toast('Budget reicht nicht','Coach kann nicht verpflichtet werden.');if(t.coachId)return toast('Coach vorhanden','Beende zuerst den aktuellen Vertrag.');t.budget-=c.price;t.coachId=id;t.coachBoost=c.boost;addNews('Neuer Coach',`${c.name} kommt mit +${c.boost}% Boost.`,'COACH');save();render()}
function fireCoach(){const t=currentTeam();if(!t.coachId)return;const c=state.coaches.find(x=>x.id===t.coachId);const fee=c?Math.round(c.price*.35):0;t.budget-=fee;t.coachId=null;t.coachBoost=0;addNews('Coach entlassen',`${c?.name||'Coach'} · Vertragsstrafe ${money(fee)}.`,'COACH');save();render()}
function signSponsor(id){const s=state.sponsors.find(x=>x.id===id);if(!s)return;const t=currentTeam();t.sponsorId=id;addNews('Sponsorvertrag',`${s.name} zahlt ${money(s.weekly)} pro Woche.`,'SPONSOR');save();render();toast('Sponsor aktiv',s.name)}
function endSponsor(){currentTeam().sponsorId=null;save();render()}
function upgradeStadium(k){const t=currentTeam(),u=t.stadium.upgrades[k],cost=Math.round(STADIUM_UPGRADES[k][3]*Math.pow(1.65,u-1));if(t.budget<cost)return toast('Budget reicht nicht',money(cost));t.budget-=cost;t.stadium.upgrades[k]++;t.stadium.level=Math.max(t.stadium.level,u+1);if(k==='stands')t.stadium.capacity+=40;state.building=true;addNews('Arena-Ausbau',`${STADIUM_UPGRADES[k][0]} auf Level ${t.stadium.upgrades[k]}.`,'ARENA');save();render();setTimeout(()=>{state.building=false;render()},1500)}
function renameStadium(){const t=currentTeam();const n=prompt('Neuer Arenaname',t.stadium.name||`${t.name} Street Arena`);if(!n)return;t.stadium.name=n.trim();save();render()}
function youthScout(){const p=createPlayer(`${choose(FIRST_NAMES)} ${choose(LAST_NAMES)}`,choose(['ZOM','LF','RF','ST']),rand(58,72),rand(70000,160000),currentTeam().id);currentTeam().roster.push(p);addNews('Jugendtalent',`${p.name} wurde aus der Akademie entdeckt.`,'JUGEND');save();render();toast('Talent entdeckt',p.name)}
function draftOpen(type){const d=DRAFTS[type],t=currentTeam();if(t.budget<d.price)return toast('Budget reicht nicht',money(d.price));const pool=Array.from({length:d.count},()=>createPlayer(`${choose(FIRST_NAMES)} ${choose(LAST_NAMES)}`,choose(POS),rand(d.min,d.max),rand(250000,1200000),null));state.selectedDraft={type,pool,pick:d.pick};modal(`${d.name}`,`<p class="note">Wähle ${d.pick} Spieler.</p><div class="stack">${pool.map(p=>`<label class="check" style="border:1px solid #2b3530;padding:9px;border-radius:10px"><input type="checkbox" data-draft-select="${p.id}"><span><b>${esc(p.name)}</b> · ${p.pos} · ${p.rating} OVR · ${money(p.value)}</span></label>`).join('')}</div><button class="gold-btn wide" data-draft-confirm="${type}">AUSWAHL BESTÄTIGEN</button>`) }

function simulateMatch(fxId){const fx=state.fixtures.find(f=>f.id===fxId);if(!fx)return;const home=teamById(fx.home),away=teamById(fx.away);modal('SPIEL VORBEREITUNG',`<div class="grid2"><div class="stat"><b>${esc(home.name)}</b><small>HEIM · ${Math.round(teamPower(home))}</small></div><div class="stat"><b>${esc(away.name)}</b><small>AUSWÄRTS · ${Math.round(teamPower(away))}</small></div></div><p class="note">Heimvorteil, Coach-Boost, Tagesform und Aufstellung werden in der Simulation berücksichtigt.</p><button class="gold-btn wide" data-start-live="${fxId}">LIVE-SIMULATION STARTEN</button>`)}
let liveTimer=null;
function startLive(fxId){closeModal();const fx=state.fixtures.find(f=>f.id===fxId);const home=teamById(fx.home),away=teamById(fx.away);state.liveMatch={fxId,started:performance.now(),half:1,clock:0,homeScore:0,awayScore:0,events:[],ball:{x:50,y:50},players:{home:livePlayers(home,'home'),away:livePlayers(away,'away')},action:null,nextAction:performance.now()+900};modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal live-modal"><div class="live-head"><div><div class="kicker">🔴 LIVE SIMULATION</div><b>${esc(home.name)} · ${esc(away.name)}</b></div><div class="scoreline"><strong id="live-score">0 : 0</strong><small id="live-clock">00:00 · 1. HZ</small></div></div><div class="match-field" id="match-field"><div class="mid"></div><div class="circle"></div><div class="halftime" id="ht"><div class="halftime-box"><h2>HALBZEIT</h2><strong id="ht-score">0 : 0</strong><p class="note">Coach-Teamansprache · Formupdate · zweite Halbzeit startet automatisch</p></div></div></div><div class="live-feed" id="live-feed"></div><button class="ghost-btn wide" data-live-skip>SIMULATION ÜBERSPRINGEN</button></div></div>`;renderLive();liveTimer=requestAnimationFrame(tickLive)}
function livePlayers(t,side){const base=side==='home'?[{x:13,y:50},{x:29,y:30},{x:29,y:70},{x:48,y:38},{x:50,y:62}]:[{x:87,y:50},{x:71,y:70},{x:71,y:30},{x:52,y:62},{x:50,y:38}];return t.roster.slice(0,5).map((p,i)=>{const r=lineupRole(t,p,i);return {...base[i],id:p.id,name:p.name,side,move:r.move,gk:r.inGoal}})}
function addLiveEvent(text,type='') {const lm=state.liveMatch;if(!lm)return;lm.events.unshift({text,type,time:lm.clock});lm.events=lm.events.slice(0,9)}
function currentLiveHolder(){const lm=state.liveMatch;const s=lm.action?.side||'home';return lm.players[s][lm.action?.index||0]}
function chooseLiveAction(){const lm=state.liveMatch;if(!lm)return;const ball=lm.ball;const side=Math.random()<.5?'home':'away';const arr=lm.players[side];const idx=rand(0,4);const p=arr[idx];const opp=lm.players[side==='home'?'away':'home'];const nearest=opp.reduce((best,o)=>!best||Math.hypot(o.x-p.x,o.y-p.y)<Math.hypot(best.x-p.x,best.y-p.y)?o:best,null);const xTarget=clamp(p.x+(side==='home'?rand(6,18):-rand(6,18)),8,92);const yTarget=clamp(p.y+rand(-12,12),10,90);const r=Math.random();if(r<.14){lm.action={type:'corner',side,index:idx,start:[p.x,p.y],target:[xTarget,yTarget],duration:650};addLiveEvent(`${p.name} setzt zu einer Ecke an.`,'corner')}else if(r<.23){lm.action={type:'throw',side,index:idx,start:[p.x,p.y],target:[xTarget,yTarget],duration:600};addLiveEvent(`${p.name} Einwurf auf der Seite.`,'throw')}else if(r<.42){lm.action={type:'pass',side,index:idx,start:[p.x,p.y],target:[xTarget,yTarget],duration:520};addLiveEvent(`${p.name}: schneller Pass in den Raum.`)}else if(r<.56){lm.action={type:'dribble',side,index:idx,start:[p.x,p.y],target:[xTarget,yTarget],duration:680};addLiveEvent(`${p.name} zieht ins Dribbling.`)}else if(r<.74){lm.action={type:'tackle',side,index:idx,start:[p.x,p.y],target:[nearest?.x||xTarget,nearest?.y||yTarget],duration:420};addLiveEvent(`${p.name} geht entschlossen in den Zweikampf.`)}else if(r<.90){lm.action={type:'shot',side,index:idx,start:[p.x,p.y],target:[side==='home'?92:8,rand(34,66)],duration:760};addLiveEvent(`${p.name} nimmt Maß und schießt!`,'shot')}else{lm.action={type:'cross',side,index:idx,start:[p.x,p.y],target:[side==='home'?92:8,rand(18,82)],duration:850};addLiveEvent(`${p.name} bringt den Ball scharf vor das Tor.`,'corner')}lm.action.startTime=performance.now()}
function resolveLiveAction(){const lm=state.liveMatch,a=lm.action;if(!a)return;const fx=state.fixtures.find(f=>f.id===lm.fxId);const team=teamById(a.side==='home'?fx.home:fx.away);const opp=teamById(a.side==='home'?fx.away:fx.home);const idx=a.index;const p=team.roster[idx]||team.roster[0];const power=teamPower(team),oppPower=teamPower(opp);if(a.type==='shot'){const goalChance=clamp(.14+(power-oppPower)*0.003,.06,.48);const goal=Math.random()<goalChance;if(goal){if(a.side==='home')lm.homeScore++;else lm.awayScore++;addLiveEvent(`TOR! ${p.name} trifft — ${lm.homeScore}:${lm.awayScore}`,'goal')}else addLiveEvent(Math.random()<.55?'Parade! Der Torwart hält.':'Knapp vorbei!','save')}else if(a.type==='tackle'){if(Math.random()<.18)addLiveEvent(`${p.name} sieht Gelb.`,'card')}else if(a.type==='corner'){addLiveEvent('Eckball bringt die Abwehr unter Druck.','corner')}lm.action=null;lm.nextAction=performance.now()+rand(700,1600)}
function updateLivePlayers(){const lm=state.liveMatch;if(!lm)return;const bx=lm.ball.x,by=lm.ball.y;['home','away'].forEach(side=>{const arr=lm.players[side];arr.forEach((p,i)=>{const base=side==='home'?[{x:13,y:50},{x:29,y:30},{x:29,y:70},{x:48,y:38},{x:50,y:62}][i]:[{x:87,y:50},{x:71,y:70},{x:71,y:30},{x:52,y:62},{x:50,y:38}][i];let tx=base.x+(bx-50)*(side==='home'?.10:-.10),ty=base.y+(by-50)*.11;if(p.gk){tx=side==='home'?11:89;ty=clamp(50+(by-50)*.10,26,74)}if(lm.action&&lm.action.side===side&&lm.action.index===i){tx=lm.action.target[0];ty=lm.action.target[1]}else if(lm.action&&lm.action.side===side&&i===((lm.action.index+1)%5)){tx=clamp((lm.action.target[0]+base.x)/2,10,90);ty=clamp((lm.action.target[1]+base.y)/2,12,88)}const speed=(p.move||1)*.07;p.x+=((tx-p.x)*speed);p.y+=((ty-p.y)*speed);p.x=clamp(p.x,6,94);p.y=clamp(p.y,8,92)})})}

function tickLive(ts){const lm=state.liveMatch;if(!lm)return;const elapsed=(ts-lm.started)/1000;let gameSec=elapsed;if(elapsed<60){lm.half=1;lm.clock=elapsed}else if(elapsed<68){lm.half=0;lm.clock=60;document.getElementById('ht')?.classList.add('show');document.getElementById('ht-score').textContent=`${lm.homeScore} : ${lm.awayScore}`;}else if(elapsed<128){lm.half=2;lm.clock=60+(elapsed-68);document.getElementById('ht')?.classList.remove('show')}else{finishLive();return}updateLivePlayers();if(!lm.action&&ts>=lm.nextAction)chooseLiveAction();if(lm.action){const a=lm.action,p=clamp((ts-a.startTime)/a.duration,0,1),e=p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2;lm.ball.x=a.start[0]+(a.target[0]-a.start[0])*e;lm.ball.y=a.start[1]+(a.target[1]-a.start[1])*e;if(p>=1)resolveLiveAction()}else{lm.ball.x=clamp(lm.ball.x+Math.sin(ts/400)*0.12,8,92);lm.ball.y=clamp(lm.ball.y+Math.cos(ts/500)*0.12,10,90)}renderLive();liveTimer=requestAnimationFrame(tickLive)}
function renderLive(){const lm=state.liveMatch;if(!lm)return;const fs=document.getElementById('match-field');if(!fs)return;fs.querySelectorAll('.match-player,.match-ball').forEach(x=>x.remove());['home','away'].forEach(side=>lm.players[side].forEach((p,i)=>{const el=document.createElement('div');el.className=`match-player ${side}`;el.style.left=p.x+'%';el.style.top=p.y+'%';el.innerHTML=`<img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect x='7' y='6' width='26' height='30' rx='7' fill='${side==='home'?'%23f4d03f':'%233b82f6'}'/%3E%3Ccircle cx='20' cy='13' r='6' fill='%23e5b89f'/%3E%3C/svg%3E"><b>${esc(p.name.split(' ')[0])}</b>`;fs.appendChild(el)}));const ball=document.createElement('div');ball.className='match-ball';ball.style.left=lm.ball.x+'%';ball.style.top=lm.ball.y+'%';fs.appendChild(ball);document.getElementById('live-score').textContent=`${lm.homeScore} : ${lm.awayScore}`;document.getElementById('live-clock').textContent=`${String(Math.floor(lm.clock/60)).padStart(2,'0')}:${String(Math.floor(lm.clock%60)).padStart(2,'0')} · ${lm.half===1?'1. HZ':'2. HZ'}`;document.getElementById('live-feed').innerHTML=lm.events.map(e=>`<div class="event ${e.type}"><b>${String(Math.floor(e.time/60)).padStart(2,'0')}:${String(Math.floor(e.time%60)).padStart(2,'0')}</b> · ${esc(e.text)}</div>`).join('')}
function finishLive(){if(liveTimer)cancelAnimationFrame(liveTimer);const lm=state.liveMatch;if(!lm)return;const fx=state.fixtures.find(f=>f.id===lm.fxId);fx.played=true;fx.homeScore=lm.homeScore;fx.awayScore=lm.awayScore;const h=teamById(fx.home),a=teamById(fx.away);h.financials.income+=Math.round(2000+lm.homeScore*900);a.financials.income+=Math.round(1200+lm.awayScore*550);if(fx.home===state.userTeamId||fx.away===state.userTeamId){const won=(fx.home===state.userTeamId?lm.homeScore>lm.awayScore:lm.awayScore>lm.homeScore);currentTeam().budget+=won?3500:700;addNews(won?'Sieg!':'Spiel beendet',`${h.name} ${lm.homeScore}:${lm.awayScore} ${a.name}.`,'MATCH')}simulateOtherFixturesOnDate(fx.date,fx.id);state.liveMatch=null;endWeek();closeModal();render()}
function setFormation(f){const t=currentTeam();state.formation=f;const d=defaultCoords();t.positions={...(t.positions||{})};t.roster.slice(0,5).forEach((p,i)=>t.positions[p.id]=d[i]);save();render()}
let drag=null;
document.addEventListener('pointerdown',e=>{const el=e.target.closest?.('[data-drag-player]');if(!el)return;const field=el.closest('[data-lineup-field]');if(!field)return;e.preventDefault();drag={el,field,id:el.dataset.dragPlayer,rect:field.getBoundingClientRect(),startX:e.clientX,startY:e.clientY,moved:false,pointerId:e.pointerId};el.classList.add('dragging');try{el.setPointerCapture(e.pointerId)}catch{}} ,{passive:false});
document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();const d=drag,dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(Math.hypot(dx,dy)>4)d.moved=true;if(!d.moved)return;const x=clamp((e.clientX-d.rect.left)/d.rect.width*100,5,95),y=clamp((e.clientY-d.rect.top)/d.rect.height*100,7,93);drag.el.style.left=x+'%';drag.el.style.top=y+'%';currentTeam().positions[drag.id]={x,y};},{passive:false});
document.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointerId)return;const moved=drag.moved;drag.el.classList.remove('dragging');drag=null;if(moved){save();render()}});
document.addEventListener('pointercancel',()=>{if(drag){drag.el.classList.remove('dragging');drag=null}});

// Main click delegation

document.addEventListener('click',e=>{
 if(e.target.classList.contains('modal-backdrop')){closeModal();return}
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.closeModal!==undefined||e.target.classList.contains('modal-backdrop')){closeModal();return}
 if(b.dataset.startTeam){state.userTeamId=b.dataset.startTeam;localStorage.setItem(FIRST,'1');save();closeModal();render();return}
 if(b.dataset.page){state.page=b.dataset.page;render();return}
 if(b.dataset.welcomeDone){localStorage.setItem(FIRST,'1');closeModal();return}
 if(b.dataset.simulate){simulateMatch(b.dataset.simulate);return}
 if(b.dataset.startLive){startLive(b.dataset.startLive);return}
 if(b.dataset.liveSkip){finishLive();return}
 if(b.dataset.marketFilter!==undefined){state.marketFilter=b.dataset.marketFilter;render();return}
 if(b.dataset.offer){openOffer(b.dataset.offer,'offer');return}
 if(b.dataset.inquiry){openOffer(b.dataset.inquiry,'inquiry');return}
 if(b.dataset.trade){openOffer(b.dataset.trade,'trade');return}
 if(b.dataset.sendOffer){sendOffer(b.dataset.sendOffer,b.dataset.offerMode||'offer');return}
 if(b.dataset.acceptCounter){const o=state.offers.find(x=>x.id===b.dataset.acceptCounter);if(o){o.status='accepted';const p=playerById(o.playerId);if(p){currentTeam().budget-=o.counterFee||o.fee;currentTeam().roster.push({...p,id:uid('p'),teamId:state.userTeamId,salary:o.counterSalary||o.salary});if(p.sourceTeamId)teamById(p.sourceTeamId).roster=teamById(p.sourceTeamId).roster.filter(x=>x.id!==p.id);else state.freeMarket=state.freeMarket.filter(x=>x.id!==p.id)}save();render();toast('Transfer abgeschlossen',o.playerName)}return}
 if(b.dataset.playerOfferAccept){const o=state.playerOffers.find(x=>x.id===b.dataset.playerOfferAccept);if(o){const p=currentTeam().roster.find(x=>x.id===o.playerId);if(p){currentTeam().budget+=o.amount;currentTeam().roster=currentTeam().roster.filter(x=>x.id!==p.id);o.status='accepted';addNews('Spieler verkauft',`${p.name} wechselt zu ${o.teamName}.`,'TRANSFER');save();render()}}return}
 if(b.dataset.playerOfferReject){const o=state.playerOffers.find(x=>x.id===b.dataset.playerOfferReject);if(o){o.status='rejected';save();render()}return}
 if(b.dataset.sponsor){signSponsor(b.dataset.sponsor);return}
 if(b.dataset.sponsorEnd){endSponsor();return}
 if(b.dataset.hireCoach){hireCoach(b.dataset.hireCoach);return}
 if(b.dataset.fireCoach){fireCoach();return}
 if(b.dataset.upgrade){upgradeStadium(b.dataset.upgrade);return}
 if(b.dataset.renameStadium){renameStadium();return}
 if(b.dataset.youthScout){youthScout();return}
 if(b.dataset.formation){setFormation(b.dataset.formation);return}
 if(b.dataset.saveGame){save();return}
 if(b.dataset.export){exportSave();return}
 if(b.dataset.import){importSave();return}
 if(b.dataset.reset){resetGame();return}
 if(b.dataset.saveProfile){state.manager=document.getElementById('manager-name').value.trim()||'Manager';const old=currentTeam().name;const wanted=document.getElementById('club-name').value.trim()||old;if(wanted!==old){currentTeam().name=wanted;addNews('Vereinsname geändert',`${old} heißt jetzt ${wanted}.`,'VEREIN')}save();render();return}
 if(b.dataset.draft){draftOpen(b.dataset.draft);return}
 if(b.dataset.draftConfirm){const ids=[...modalRoot.querySelectorAll('[data-draft-select]:checked')].map(x=>x.dataset.draftSelect);const d=state.selectedDraft;if(!d||ids.length!==d.pick)return toast('Auswahl prüfen',`Du musst ${d.pick} Spieler wählen.`);const t=currentTeam();t.budget-=DRAFTS[d.type].price;ids.map(id=>d.pool.find(p=>p.id===id)).forEach(p=>{p.teamId=t.id;t.roster.push(p)});state.selectedDraft=null;closeModal();save();render();toast('Draft abgeschlossen','Talente wurden verpflichtet.');return}
});

// Market filter property name compatibility
Object.defineProperty(document,'_sknoop',{value:true,enumerable:false});
setInterval(()=>{resolveOffers();if(state.page!=='home'&&state.page!=='games')return;},5000);

boot();

